import Link from 'next/link'
import { EventHeader } from '@/components/EventHeader'
import { getEventContext } from '@/lib/event'
import { saveNoteAction } from '@/app/actions/game'

export default async function Challenges({params}:{params:Promise<{id:string}>}){
  const {id}=await params
  const {user,supabase,event,memberCount,isAdmin}=await getEventContext(id)
  const started=new Date(event.start_at)<=new Date()
  if(!started&&!isAdmin)return <><EventHeader event={event} memberCount={memberCount} isAdmin={isAdmin} active="challenges"/><section className="prelaunch empty-state"><div className="bigicon">🗺️</div><h2>La carte est encore roulée.</h2><p>L’admin prépare les défis en secret. Ils seront révélés automatiquement au départ.</p></section></>
  const {data:challenges}=await supabase.from('challenges').select('*').eq('event_id',id).eq('platform_removed',false).order('created_at')
  const {data:notes}=await supabase.from('challenge_notes').select('*').eq('user_id',user.id)
  const {data:approved}=await supabase.from('attempts').select('challenge_id,status').eq('event_id',id).eq('user_id',user.id)
  const nmap=new Map((notes||[]).map((n:any)=>[n.challenge_id,n]));const amap=new Map((approved||[]).map((a:any)=>[a.challenge_id,a.status]))
  return <><EventHeader event={event} memberCount={memberCount} isAdmin={isAdmin} active="challenges"/><section className="pagehead compact"><div><div className="eyebrow">LA LISTE COMMUNE</div><h2>{isAdmin&&!started?'Préparation secrète des défis':'Défis'}</h2><p>{isAdmin&&!started?'Toi seul peux voir cette liste avant le départ.':'Planifie ta stratégie et publie une preuve quand tu passes à l’action.'}</p></div>{isAdmin&&<Link className="button" href={`/event/${id}/admin`}>＋ Ajouter</Link>}</section><div className="challengegrid">{(challenges||[]).map((c:any)=>{const note:any=nmap.get(c.id);const status=amap.get(c.id);return <article className="card challenge-card" key={c.id}><div className="row"><span className={`badge ${c.challenge_type==='exclusive'?'gold':''}`}>{c.challenge_type==='exclusive'?'EXCLUSIF':'CLASSIQUE'}</span><strong>{c.points} pts</strong></div><h2>{c.title}</h2><p>{c.description}</p><div className="challenge-actions"><span className={`badge ${status==='approved'?'good':status==='voting'?'wait':''}`}>{status==='approved'?'Validé':status==='voting'||status==='submitted'?'En attente':'À faire'}</span>{started&&!status&&<Link className="button small" href={`/event/${id}/attempt/new?challenge=${c.id}`}>Publier ma tentative</Link>}</div>{started&&<details className="challenge-note"><summary>📝 Ma stratégie privée</summary><form action={saveNoteAction.bind(null,c.id,id)}><label>Note<textarea name="note" rows={2} defaultValue={note?.note||''}/></label><label>Date prévue<input name="planned_date" type="date" defaultValue={note?.planned_date||''}/></label><label>Priorité<select name="priority" defaultValue={note?.priority||'normal'}><option value="low">Basse</option><option value="normal">Normale</option><option value="high">Haute</option></select></label><label className="checkbox"><input type="checkbox" name="favorite" defaultChecked={!!note?.favorite}/> Favori</label><button className="button ghost small">Enregistrer</button></form></details>}</article>})}{!(challenges||[]).length&&<div className="card empty-state"><h2>Aucun défi</h2><p>{isAdmin?'Ajoute le premier défi avant de partir.':'La liste est vide.'}</p></div>}</div></>
}
