import { notFound } from 'next/navigation'
import { EventHeader } from '@/components/EventHeader'
import { Flash } from '@/components/Flash'
import { getEventContext } from '@/lib/event'
import { addChallengeAction, updateEventInfoAction, regenerateInviteAction, banMemberAction } from '@/app/actions/game'
import { Avatar } from '@/components/Avatar'
import { fmtDate } from '@/lib/format'

export default async function EventAdmin({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
  const {id}=await params;const sp=await searchParams;const {user,supabase,event,memberCount,isAdmin}=await getEventContext(id);if(!isAdmin)notFound()
  const {data:members}=await supabase.from('event_members').select('*').eq('event_id',id).eq('status','active').order('joined_at');const ids=(members||[]).map((m:any)=>m.user_id);let profiles:any[]=[];if(ids.length){const {data}=await supabase.from('profiles').select('id,username,avatar_url').in('id',ids);profiles=data||[]}const pmap=new Map(profiles.map((p:any)=>[p.id,p]));const started=new Date(event.start_at)<=new Date()
  return <><Flash message={sp.m} error={sp.e}/><EventHeader event={event} memberCount={memberCount} isAdmin={isAdmin} active="admin"/><div className="admin-section"><section><form className="card" action={updateEventInfoAction.bind(null,id)}><div className="eyebrow">PARAMÈTRES MODIFIABLES</div><h2>Informations du camp</h2><label>Nom<input name="name" defaultValue={event.name} required/></label><label>Description<textarea name="description" rows={3} defaultValue={event.description}/></label><label>Récompense<input name="reward_text" defaultValue={event.reward_text||''}/></label><label>Visibilité<select name="visibility" defaultValue={event.visibility}><option value="private">Privée</option><option value="public">Publique</option></select></label><label>Limite membres<input type="number" min={memberCount} name="max_members" defaultValue={event.max_members||''} placeholder="Vide = illimité"/></label><button className="button">Enregistrer</button></form>
  <form className="card" action={addChallengeAction.bind(null,id)}><div className="eyebrow">{started?'NOUVEAU DÉFI':'PRÉPARATION SECRÈTE'}</div><h2>Ajouter un défi</h2><p className="hint">Une fois l’expédition démarrée, les défis existants ne sont plus modifiables ni supprimables.</p><label>Titre<input name="title" required/></label><label>Description<textarea name="description" rows={3}/></label><div className="formgrid"><label>Points<input type="number" min={1} name="points" defaultValue={1}/></label><label>Type<select name="challenge_type"><option value="classic">Classique</option><option value="exclusive">Exclusif · premier validé</option></select></label></div><button className="button">Ajouter le défi</button></form></section>
  <aside><div className="card"><h2>Invitations</h2><p>Code actuel :</p><div className="invitecode">{event.invite_code}</div><form action={regenerateInviteAction.bind(null,id)}><button className="button ghost small">Régénérer</button></form></div><div className="card"><h2>Règles verrouillées 🔒</h2><div className="rule-lock"><span>Départ</span><strong>{fmtDate(event.start_at)}</strong></div><div className="rule-lock"><span>Fin</span><strong>{fmtDate(event.end_at)}</strong></div><div className="rule-lock"><span>Vote</span><strong>{event.vote_duration_hours} h · {Math.round(Number(event.reject_threshold)*100)}%</strong></div><div className="rule-lock"><span>Classement</span><strong>{event.leaderboard_visibility}</strong></div><div className="rule-lock"><span>Mode secret</span><strong>{event.secret_submissions?'Oui':'Non'}</strong></div></div><div className="card"><h2>Gestion membres</h2>{(members||[]).filter((m:any)=>m.user_id!==user.id).map((m:any)=>{const p:any=pmap.get(m.user_id);return <div className="memberrow" key={m.id}><Avatar username={p?.username} url={p?.avatar_url} size="sm"/><strong>{p?.username}</strong><form action={banMemberAction.bind(null,id,m.user_id)}><input type="hidden" name="reason" value="Banni par l’administrateur"/><button className="linkbtn dangertext">Bannir</button></form></div>})}</div></aside></div></>
}
