'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

function localInput(d:Date){const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)}

export function CreateEventForm(){
  const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const defaults=useMemo(()=>{const s=new Date();s.setDate(s.getDate()+7);s.setMinutes(0,0,0);const e=new Date(s);e.setFullYear(e.getFullYear()+1);return{start:localInput(s),end:localInput(e)}},[])
  const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const max=String(f.get('max_members')||'').trim();const start=new Date(String(f.get('start_at')));const end=new Date(String(f.get('end_at')));const {data,error}=await supabase.rpc('create_event',{p_name:String(f.get('name')||''),p_description:String(f.get('description')||''),p_visibility:String(f.get('visibility')||'private'),p_max_members:max?Number(max):null,p_start_at:start.toISOString(),p_end_at:end.toISOString(),p_reward_text:String(f.get('reward_text')||''),p_points_mode:String(f.get('points_mode')||'uniform'),p_default_points:Number(f.get('default_points')||1),p_vote_duration_hours:Number(f.get('vote_duration_hours')||168),p_reject_threshold:Number(f.get('reject_threshold')||50)/100,p_vote_visibility:String(f.get('vote_visibility')||'hidden'),p_leaderboard_visibility:String(f.get('leaderboard_visibility')||'visible'),p_secret_submissions:f.get('secret_submissions')==='on'});if(error||!data)throw error||new Error('Impossible de créer l’expédition.');router.push(`/event/${data}?m=${encodeURIComponent('Expédition créée. Le camp est ouvert !')}`);router.refresh()}catch(err:any){setError(err?.message||'Impossible de créer l’expédition.')}finally{setBusy(false)}}
  return <form onSubmit={submit}>{error&&<div className="flash err">{error}</div>}<div className="formgrid"><label>Nom<input name="name" required minLength={3} placeholder="La Grande Expédition"/></label><label>Visibilité<select name="visibility"><option value="private">Privée · code/lien</option><option value="public">Publique · visible dans Explorer</option></select></label><label className="span2">Description<textarea name="description" rows={3} placeholder="Une année pour faire un maximum de défis absurdes."/></label><label>Départ<input type="datetime-local" name="start_at" defaultValue={defaults.start} required/></label><label>Fin<input type="datetime-local" name="end_at" defaultValue={defaults.end} required/></label><label>Limite participants<input type="number" name="max_members" min={1} placeholder="Vide = illimité"/></label><label>Récompense facultative<input name="reward_text" placeholder="Le dernier paye le resto…"/></label><label>Mode de points<select name="points_mode"><option value="uniform">Tous les défis = même valeur</option><option value="custom">Points personnalisés par défi</option></select></label><label>Points par défaut<input type="number" name="default_points" defaultValue={1} min={1}/></label><label>Durée de vote<select name="vote_duration_hours" defaultValue="168"><option value="24">24 heures</option><option value="72">3 jours</option><option value="168">7 jours</option><option value="336">14 jours</option></select></label><label>Seuil de refus (%)<input type="number" name="reject_threshold" defaultValue={50} min={1} max={100}/></label><label>Votes<select name="vote_visibility"><option value="hidden">Cachés pendant le vote</option><option value="visible">Visibles</option></select></label><label>Classement<select name="leaderboard_visibility"><option value="visible">Visible</option><option value="hidden">Caché jusqu’à la fin</option></select></label><label className="checkbox span2"><input type="checkbox" name="secret_submissions"/> Mode secret : les preuves des autres sont révélées à la fin</label></div><button className="button" disabled={busy}>{busy?'Création…':'Créer l’expédition'}</button></form>
}
